// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default']
    EConsole: typeof import('./src/components/editor-ui/EConsole.vue')['default']
    EContainer: typeof import('./src/components/editor-ui/EContainer.vue')['default']
    EEditor: typeof import('./src/components/editor-ui/EEditor.vue')['default']
    EMessage: typeof import('./src/components/editor-ui/EMessage.vue')['default']
    EPreview: typeof import('./src/components/editor-ui/EPreview.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NCol: typeof import('naive-ui')['NCol']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NModal: typeof import('naive-ui')['NModal']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NPopSelect: typeof import('naive-ui')['NPopSelect']
    NRow: typeof import('naive-ui')['NRow']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SCodeMirror: typeof import('./src/components/codeMirror/SCodeMirror.vue')['default']
    SMenu: typeof import('./src/components/SMenu.vue')['default']
    TheImage: typeof import('./src/components/TheImage.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
  }
}
